### ISSUE TITLE
Provide example for Grid Layout

### ISSUE THREAD

**Issue by fhaust** [timbod7/haskell-chart#102]
I am trying to get several plots into a grid layout, but they end up being scaled wrong:

![stuff](https://cloud.githubusercontent.com/assets/3219263/10389855/ce0c0614-6e74-11e5-8da3-e19df6c115d9.png)

This is using `Chart-1.5.3` and `Chart-cairo-1.5.1`. 

The individual plotting functions look like this:

    plotEvents' :: S.Vector (V3 Double) -> EC (Layout Double Double) ()
    plotEvents' es = do
      layout_background .= solidFillStyle (opaque white)
      layout_foreground .= opaque black
  
      plot $ liftEC $ do
        area_spots_4d_max_radius .= 50
        area_spots_4d_values .= eventsTo4dPoints es
        area_spots_4d_palette .= brewerSet YlGn 9
        area_spots_4d_opacity .= 0.5

which I try to combine like this:

    renderableToFile def "out.png" $ toRenderable $ ((tval . execEC $ plotEvents' (events !! 0)) .|. (tval . execEC $ plotEvents' (events !! 1)) ./. (tval . execEC $ plotEvents' (events !! 2)))

I have tried several ways to combine these, with and without the execEC and different combinations of placing the `toRenderables` with no success. Could you provide an example on how to use the grid combinators for the wiki?

**Comment by timbod7** [comment]
The functions and data types in `Graphics.Rendering.Chart.Grid` were written to position the internal elemnts of charts (ie putting the axes at the sides of the plot area, the title at the top etc.). They weren't actually  intended for positioning charts themselves in a grid. Nevertheless, it seems to be a common assumption. I'm sure that with a bit of fiddling, they could be used for this, but the results would not be entirely satisfactory - Just laying charts out in a grid without constraining their internal elements to line up will look untidy.

The `StackedLayouts` code solves this problem for correctly vertically aligning charts. I think a generalisation of this to a `GriddedLayouts` type would be the right way to go.

**Comment by mstksg** [comment]
Just checking, is there any way you would implement "gridded" layouts (like matlab subplots) of this type in current Charts?

**Comment by timbod7** [comment]
Currently only a vertical stack is implemented (via `StackedLayouts`).

**Comment by mstksg** [comment]
Right; do you think there's any way to hack a solution at the moment? :)  or any tips on where I might start if I wanted to implement it more formally and submit a PR?

**Comment by timbod7** [comment]
As the per the original request, it's probably possible to hack something with the existing low-level grid functions, but it will be fiddly and the alignment won't in general be correct.

I think the solution is to refactor the existing Layout rendering logic into two steps, where the first stem goes to a unparameterised holder type which has all of the chart elements as distinct renderables. Then these can be composed using the low-level grid functions.

I'll try and flesh this idea out soon.

**Comment by mstksg** [comment]
thanks for the prompt replies!

**Comment by timbod7** [comment]
I started to look at doing this properly (ie to ensure that the elements of each plot are always aligned). However, there is an [existing test (test1a)][1] (which had slipped my mind) that shows how it can be done with the existing codebase.:

![test1a](https://cloud.githubusercontent.com/assets/1996446/13389693/028db4a4-df1e-11e5-9e20-ca10de633dec.png)

Does that help?

[1]:https://github.com/timbod7/haskell-chart/blob/master/chart-tests/tests/Tests.hs#L41

**Comment by mstksg** [comment]
I had actually already hacked something together with a similar effect, but seeing this this does help/give me more to work with, thanks! :)

**Comment by timbod7** [comment]
Resolved with a [new example][1] on the wiki, that relies on the [newly exposed][2] function to create grids from layouts.

[1]:https://github.com/timbod7/haskell-chart/wiki/example-13
[2]:https://github.com/timbod7/haskell-chart/commit/d0a8c30f14a097161f03e59c6bd251c965bbc433
