### ISSUE TITLE
sample 0 does not work 

### ISSUE THREAD

**Issue by ra1u** [timbod7/haskell-chart#107]
from https://github.com/timbod7/haskell-chart/wiki/example-0

    $ ghci -package Chart-gtk
    ...
    Prelude> :m Graphics.Rendering.Chart.Gtk.Simple
    Prelude Graphics.Rendering.Chart.Gtk.Simple> plotWindow [0,0.1..2.9] sin

gives error importing module

    :m Graphics.Rendering.Chart.Gtk.Simple

    <no location info>:
        Could not find module ‘Graphics.Rendering.Chart.Gtk.Simple’
        Perhaps you meant
          Graphics.Rendering.Chart.Gtk (from Chart-gtk-1.5.1@Chart_HsGiW5NsZSREvKa0e31bJc)
          Graphics.Rendering.Chart.Utils (from Chart-1.5.4@Chart_HXbipHC6vp89mmXsXJtaWN)
          Graphics.Rendering.Chart.Grid (from Chart-1.5.4@Chart_HXbipHC6vp89mmXsXJtaWN)

**Comment by timbod7** [comment]
Example 0 is defunct, as the `Simple` module was replaced by the `Easy` some time ago.

Thanks for pointing this out - I've removed it from the wiki.
