### ISSUE TITLE
Add Chart-diagrams to Stackage?

### ISSUE THREAD

**Issue by sid-kap** [timbod7/haskell-chart#108]
Is someone planning to add Chart-diagrams to Stackage? I noticed that Chart and Chart-cairo are already there.

I believe it might be as easy as forking github.com/fpco/stackage and adding the following to build-constraints.yaml:
```
"<your name> <your email> @<your github id>":
    - Chart-diagrams
```

I could go ahead and make the PR myself (anyone is allowed to do this), but I wanted to ask here because the maintainers might prefer to do it themselves.

By the way, thanks for all of the maintainers' hard work on this library! I'm gradually drifting from using R as my default plotting tool to using Chart.

**Comment by timbod7** [comment]
Chart-diagrams was previously in stackage. It was removed as per this issue:

https://github.com/fpco/stackage/issues/541

Basically, the listed downstream dependencies (SVGFonts, BlazeSVG) weren't in stackage, and I didn't want to take responsibility for them in the stackage world.If you are happy to be the stackage maintainer for chart-diagrams and its dependencies, I'd be delighted!

**Comment by sid-kap** [comment]
Thanks for the quick reply!

I've sent a message to the maintainer of tuple and OneTuple, so if that goes into stackage, that would be a great start. I'll try to contact the maintainers of SVGFonts and BlazeSVG as well. I suppose I wouldn't mind being the stackage maintainer for these projects --- I'll think about it and get back to you!

**Comment by timbod7** [comment]
I'll grant you commit access to this repo if that helps.

**Comment by sid-kap** [comment]
I decided that I'd like to be the stackage maintainer for Chart-diagrams and its dependencies. I sent a pull request to stackage at https://github.com/fpco/stackage/pull/1252.

**Comment by sid-kap** [comment]
Unfortunately, I am not able to get this into stackage at the moment because the version of Chart-diagrams requires lucid-svg < 0.6, while the version of lucid-svg in Stackage right now is 0.6.0.1. (See https://travis-ci.org/fpco/stackage/builds/112275892.) 

This is my first time adding a project to Stackage, so I may be wrong, but my guess is that this will work only when the current master-branch of Chart-diagrams (which has the updated version bounds, which were added in the PR https://github.com/timbod7/haskell-chart/pull/109) is released to Hackage. Is this correct? If so, would you be able to do a minor release for the purpose of getting Chart-diagrams to work with Stackage?

**Comment by timbod7** [comment]
Rather than doing a new release I've updated the metadata on hackage so
that chart-diagrams should now build against lucid-svg < 0.7. I've not done
it this way before.

Please let me know if it fixes your issue.

Tim

**Comment by sid-kap** [comment]
This worked. [The PR](https://github.com/fpco/stackage/pull/1252) has been merged. Thanks!
