### ISSUE TITLE
Why have multiple backends?

### ISSUE THREAD

**Issue by sid-kap** [timbod7/haskell-chart#110]
I want to preface this question by saying that I really like the Chart library as it is, and I appreciate all the time and hard work that the maintainers put into this project. I realize that the original version of this post was arrogant in that I assumed that I understood the reasoning behind the maintainers' decisions, even though I actually don't know anything about those decisions. I have revised my post accordingly.

----

I'm kind of curious why Chart chooses to have two backends (Diagrams and Cairo) instead of only using Diagrams.

Diagrams can currently compile to many backends (cairo, GTK, postscript, rasterific, canvas, svg), and so if we removed the chart-cairo code, people could still compile using cairo by going through Diagrams.

Furthermore, depending on only Diagrams could maybe allow for simpler code. It seems to me that many modules in Chart, such as Chart.Drawing, Chart.Geometry, Chart.Grid, exist solely for the sake of having an abstract, non-Diagrams-specific, backend. If we had only one backend, we could simply use Diagrams types here. Simpler code might also make it easier to contribute to Chart.

Finally, tight integration with Diagrams could enable people to make new, cool things by taking advantage of the diagrams ecosystem. For example, if Chart simply generated a Diagram object, someone could easily implement [lattice graphs](http://www.statmethods.net/advgraphs/trellis.html) using standard Diagrams functions to arrange diagrams side-by-side. (I'm not saying that this would be impossible using Chart functions, but I would guess that the Diagrams ecosystem might include more helper functions that make doing cool things like this easy.)

A lot of this comes from my bias as a library user who doesn't understand the implementations of the libraries. I recently started using Diagrams and was very impressed. As a result, I thought that it would be nice for all of Haskell's graphics tools to be under the same umbrella, in this case the Diagrams library. I'm sure the maintainers had good reasons to keep Chart independent of Diagrams, and I'd like to understand them.

**Comment by timbod7** [comment]
There are 2 main reasons for having multiple backends:

* historical: the chart library predates diagrams
* performance: cairo is at least 20x faster that the diagrams backend

The performance was most recently raised in [this issue](https://github.com/timbod7/haskell-chart/issues/105). In a nutshell, people would like the diagrams backend to be faster, but no-one has yet volunteered to make it happen. 

The abstraction of the backend, and the implementation of the diagrams backend was done as a google summer of code project in 2013. Jan Bracker did an excellent job on this work, but there wasn't sufficient time available to profile the resulting code and address performance. It's still unclear whether the issues lie in the diagrams library itself, or perhaps more likely, in the chart libraries use of it.

Also, Diagrams actually lacks some key features that were awkward to work around. The library (still?) has no knowledge of text metrics, which are critical to the clean display of labels in the axes and elsewhere on the plots.

**Comment by bergey** [comment]
> It's still unclear whether the issues lie in the diagrams library itself, or perhaps more likely, in the chart libraries use of it.

I'd guess some of each.  I expect there's low-hanging fruit in making Diagrams faster.  I'd be happy to help from the Diagrams side, if someone has time to profile and identify hotspots.

The text problem is harder.  Many of the target formats supported by Diagrams Backends themselves have no text metrics.  SVG and HTML canvas are especially bad because font choice is controlled by the viewer program.  The Cairo Backend is the only one that does a really good job with fonts, but I don't see much benefit to Chart from using Diagrams if it still uses Cairo.  I'd love a way to get complete font support in say, diagrams-rasterific, but I expect it's a lot of work.

**Comment by timbod7** [comment]
In summary, I'm not really open to dropping support for cairo and only supporting the diagrams backend until the diagrams atop cairo is equivalent in capability to the native cairo backend. I generally always use the native cairo backend (for performance).

I'd offer enthusiastic support for anyone who wants to improve the diagrams backend, but don't have much time  to look at this now.

**Comment by sid-kap** [comment]
Thank you to both of you for your replies! I think I understand the situation much better now, and I now know a few directions I can take when I have time to contribute. 

I'm going to close this issue for now, and I'll let either of you know if I find something that makes the diagrams backend or the diagrams library faster, or that improves the text handling of the diagrams backends. Thanks for your time!
