### ISSUE TITLE
Switch to scientific notation for labels if they're too long

### ISSUE THREAD

**Issue by Shimuuar** [timbod7/haskell-chart#121]
Motivating example:

![download](https://cloud.githubusercontent.com/assets/100394/15332333/3f3b66b8-1c76-11e6-9a97-c61cb9a1beaa.png)

**Comment by timbod7** [comment]
You can use the `la_labelf` attribute on `LinearAxisParams` to provide your own mapping from values to labels.

Having said that, I'd be happy for a patch to the default label function that switched to scientific mode automatically. The relevant function is [showD][1]

[1]:https://github.com/timbod7/haskell-chart/blob/master/chart/Graphics/Rendering/Chart/Axis/Floating.hs#L80

**Comment by ghorn** [comment]
I looked at patching `showD` but there is a possible loss of information in its current form. Consider plotting

`[1000000.00000001, 1000000.00000002, 1000000.00000003]`

If you switch to scientific notation with a maximum number of digits, like 3, you would get

`["1.000e3", "1.000e3", "1.000e3"]`

Matplotlib solves this by doing something like 

`1e6 + [1e-8, 2e-8, 3e-8]`

I think you would have to modify the type of `makeAxis` to fix this issue:
```haskell
-- current type
makeAxis :: PlotValue x => (x -> String) -> ([x],[x],[x]) -> AxisData x

-- possible fix, takes a range as well as a value
makeAxis :: PlotValue x => (x -> (x, x) -> String) -> ([x],[x],[x]) -> AxisData x

-- More general type. Promises to return a list of the same length
makeAxis :: PlotValue x => ([x] -> [String]) -> ([x],[x],[x]) -> AxisData x
```

**Comment by timbod7** [comment]
Yikes. I never thought that generating a label would depend on the other
values.

I prefer the second more, general formulation.

**Comment by ghorn** [comment]
> I prefer the second more, general formulation.

Shall I throw an `error` if the lengths aren't equal?

**Comment by timbod7** [comment]
It's a buggy implementation, so error is probably ok.

**Comment by ghorn** [comment]
I implemented a preliminary fix for this. I tried to err on the conservative side, that is, when in doubt fall back to the old implementation

**Comment by ghorn** [comment]
I also added doctests here https://github.com/ghorn/haskell-chart/blob/master/chart/Graphics/Rendering/Chart/Axis/Floating.hs#L89-L114.

If we find bad results we want to improve on, we can just keep adding them to the tests

**Comment by Shimuuar** [comment]
I just want to add rather extreme illustration of need for scientific notation. This plot is accidental I plotted wrong in range but it illustrates how bad things can get

![admin-3](https://cloud.githubusercontent.com/assets/100394/16394551/e4cd2f4c-3cc6-11e6-97bd-2fabe54e455a.png)

**Comment by timbod7** [comment]
fixed with https://github.com/timbod7/haskell-chart/pull/127
