### ISSUE TITLE
Release that supports data-default-class-0.1.2.0

### ISSUE THREAD

**Issue by borsboom** [timbod7/haskell-chart#131]
It looks like `master` has already been updated in https://github.com/timbod7/haskell-chart/commit/51c7ed118bac0d0bcfd0654535a717f1a4d92315.  Can we have a release to Hackage (or a metadata update) that includes this change?  See also https://github.com/fpco/stackage/issues/1371#issuecomment-228592530.

**Comment by timbod7** [comment]
Yers - will do this shortly.

**Comment by timbod7** [comment]
Sorry for the delay - I've just push 1.8 to hackage

**Comment by borsboom** [comment]
Thanks!
