### ISSUE TITLE
Cannot build on linux

### ISSUE THREAD

**Issue by EvgenyNerush** [timbod7/haskell-chart#138]
I can build the library on linux (tested on Arch and Debian Stretch) only if I turn off have-quartz-gtk flag, e.g. replace in stack.yaml

```
flags:
    gtk:
        have-quartz-gtk: true
```

with

`flags: {}`

Windows also don't uses Quartz, but I haven't tried to build the library on Win.
Can `have-quartz-gtk` flag be turned on/off automatically dependent on OS in some way?

**Comment by ghorn** [comment]
what is the error message?

**Comment by timbod7** [comment]
The presence of the `stack.yaml` file here is probably a mistake. It shows a "known" good version of dependences (ie the ones I tested with), but I expect that the library should build with more recent snapshots.

So if your are building inside the chart source repo,  you should edit the stack.yaml file locally to meet your needs. If you reference the chart library as a dependency of your own project, your own stack.yaml file will be used and then the `stack.yaml` file in the chart repo will be ignored in any case.

Perhaps I should call this file `stack.yaml.osx` and just symlink it locally in my own repo for development, to avoid this confusion.

(see [this discussion][1] on whether `stack.yaml` should be committed).

[1]:https://www.reddit.com/r/haskell/comments/415vne/to_ship_stackyaml_or_not_to/

**Comment by EvgenyNerush** [comment]
Thank for a quick response and explanation. I think now the issue can be closed.
