### ISSUE TITLE
Installation steps using stack are missing

### ISSUE THREAD

**Issue by Miguelme** [timbod7/haskell-chart#139]
I think we should describe the steps to install it using stack. If it isn't supported yet I think it could ease the use of this great library.

**Comment by timbod7** [comment]
Are you having problems installing the library with stack? 

If you are relying on the diagrams rendering backend, it should be no different to installing any other haskell library with stack. If you are using the cairo backend then you will need to ensure that gtk2hs is successfully installed. As per its [installation instructions][1] this can different form platform to platform.

[1]:https://wiki.haskell.org/Gtk2Hs/Installation

**Comment by Miguelme** [comment]
Hi @timbod7 the haskell-chart library failed to be installed with the command: 

`stack install chart-diagrams`

I think it would be nice to have for all the library users the instructions on how to, at least, execute the tutorial using stack.

**Comment by timbod7** [comment]
What was the error?

Did you try `stack install ./chart-diagrams`

**Comment by Miguelme** [comment]
This is the error: 
`Error parsing targets: Directory not found: ./chart-diagrams`

It looks like the chart-diagrams library is not in stackage

**Comment by timbod7** [comment]
I've created some instructions to help those not familiar with stack:

https://github.com/timbod7/haskell-chart/wiki/Getting-started

Hopefully these help??

**Comment by Miguelme** [comment]
Thanks @timbod7 ! That worked for the installation of the library with the exception that the stack command: 

`stack runghc mychart.hs`

does nothing. It just consumes a little time but it doesn't display the chart. Thanks for the help!

**Comment by timbod7** [comment]
The example script writes an svg file to the current directory.

**Comment by Miguelme** [comment]
You're right. Although, I sent you the command because it was wrong spelled in the guide. Thanks in advance.

**Comment by timbod7** [comment]
Excellent  - I'm pleased you've got it working.
