### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage.

### ISSUE THREAD

**Issue by expipiplus1** [timbod7/haskell-chart#143]
The documentation for the latest version of this package is missing on Hackage. It's possible that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by timbod7** [comment]
Looks like hackage has caught up. The docs are there now.
