### ISSUE TITLE
Export runBackendWithGlyphs in Graphics.Rendering.Chart.Backend.Diagrams

### ISSUE THREAD

**Issue by ryachza** [timbod7/haskell-chart#146]
I was wondering whether it would be reasonable to export `runBackendWithGlyphs` in `Graphics.Rendering.Chart.Backend.Diagrams`?

I would like to be able to generate `Text`/`ByteString` values using the embedded/text fonts option, and currently it appears that I would have to choose between `renderableToFile` which writes to a file, or `runBackend` which uses path fonts.

**Comment by timbod7** [comment]
Sure - I'm fine with that. Do you want to send a PR?

**Comment by ryachza** [comment]
Sure thing just wanted to check first. I would have had it together already but `stack`/`cairo`/`Windows` are not playing nicely... if it takes much longer I'll probably try a Linux VM. I know it's only a one line change but I'm not comfortable sending a PR for something I haven't built.
