### ISSUE TITLE
Question: is it possible to set the aspect ratio?

### ISSUE THREAD

**Issue by ntc2** [timbod7/haskell-chart#149]
I want a 1:1 aspect ratio, but I can't figure out how to set it.

**Comment by timbod7** [comment]
Sorry - but it's not currently possible, at least without trial and error. The layout algorithm is basically this: take the rectangle provided by the caller, and allocate space for the title, legend and axes. Use the remaining space for the plot area.

(Of course, you can manually play with the initial rectangle size to get a desired aspect ratio)

I think you'd need some sort of constraint solver to obtain a specific aspect ratio whilst simultaneously auto-scaling the axes, etc.

**Comment by ntc2** [comment]
Thanks.
