### ISSUE TITLE
The Chart-1.8.2 is not in this repository

### ISSUE THREAD

**Issue by phadej** [timbod7/haskell-chart#150]
Forgotten push?

**Comment by timbod7** [comment]
Yep. Pushed now.

**Comment by phadej** [comment]
Thanks!

**Comment by phadej** [comment]
FYI: I made a https://github.com/diagrams/diagrams-postscript/pull/22 PR allowing rendering EPS in memory, and have half-ready patch to allow `Chart-diagrams` render to lazy bytestring. I'll open a PR after&if PR gets merged&released.

Related to that. What you think of adding https://hackage.haskell.org/package/diagrams-rasterific support to `Chart-diagrams` (supporting rendering to PNG), I could do that too.

My motivation is to make stuff for web, and PNG would be a great fallback.
