### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by phadej** [timbod7/haskell-chart#156]
I see there is no CI support, I can setup one; looks like that e.g. GHC 7.8.4 support bitrotted, CI would help with those issues.

Using `cabal new-build` it should be trivial (and quite maintenance free to do, i.e. no multiple `stack.yaml` to maintain).

**Comment by timbod7** [comment]
If you can set it up, that would be great. Otherwise simple instructions for me to follow would be valuable.
