### ISSUE TITLE
Jupyter integration

### ISSUE THREAD

**Issue by alf239** [timbod7/haskell-chart#159]
Apologies for starting the discussion in an issue — it simply was the easiest way to ask. Have anyone added haskell-chart support to jupyter? Is there any projects underway? I'm eager to help, as a combination of jupyter's instant gratification and haskell's expressiveness and speed could be a killer.

**Comment by timbod7** [comment]
I've not used jupyter, but I know that others have integrated the chart library before.  See:

http://nbviewer.jupyter.org/github/gibiansky/IHaskell/blob/master/notebooks/IHaskell.ipynb

I don't think any changes to the library were required?

**Comment by alf239** [comment]
Wow, @timbod7, apologies for my poor Google skills - and thank you for the link, that's much more than what I hoped for!
