### ISSUE TITLE
stack build failed

### ISSUE THREAD

**Issue by p-alik** [timbod7/haskell-chart#163]
`stack build` failed on ubuntu 16.04. It got stuck on `gtk-0.14.6`.
https://pastebin.com/vvkUJf47

**Comment by timbod7** [comment]
Did you resolve this?

**Comment by p-alik** [comment]
Yes. 

```bash
15:29 $ git diff
diff --git a/stack.yaml b/stack.yaml
index abf83a0..34b27ce 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -7,8 +7,5 @@ packages:
 - chart-gtk/
 extra-deps:
 - gtk-0.14.6
-flags:
-  gtk:
-    # This needs to be false on Linux
-    have-quartz-gtk: true
+flags: {}
 resolver: lts-8.5
```

The solution is borrowed [here](https://stackoverflow.com/a/40197851/2789312). With regard to the post it is a general Linux issue.
