### ISSUE TITLE
Chart-diagrams: load*Fonts prints empty lines in console.

### ISSUE THREAD

**Issue by FPtje** [timbod7/haskell-chart#166]
# How to reproduce
```
putStrLn "LOAD FONTS?"
!_ <- Chart.loadCommonFonts
putStrLn "END LOAD FONTS"
```

# Output

```
LOAD FONTS?










END LOAD FONTS
```

# Motivation
A function that loads fonts should not print anything to console. It's a rather surprising and even unwanted side effect.

**Comment by timbod7** [comment]
I think this a problem with the underly SVGFonts library. This looks like the problem:

https://github.com/diagrams/SVGFonts/blob/master/src/Graphics/SVGFonts/ReadFont.hs#L343

Perhaps open a pull request to fix the issue there?

**Comment by timbod7** [comment]
I've requested a change to the SVGFonts library.

**Comment by timbod7** [comment]
`SVGFonts-1.6.0.2` has been released with the fix.  

Chart diagrams has the following cabal constraint:

```
SVGFonts >= 1.4 && < 1.7
```
so a rebuild against `SVGFonts-1.6.0.2` should fix this issue.

**Comment by FPtje** [comment]
That means I can close this issue. Thanks! Sorry for the late reply.
