### ISSUE TITLE
Chosing a Charts backend if using diagrams-cairo underneath Diagrams?

### ISSUE THREAD

**Issue by afcowie** [timbod7/haskell-chart#167]
After a huge R&D exercise, I've settled on using the Cairo backend to Diagrams to do the graphics work we need to do. Yeay. This was a bit funny, because I spent a lot of time wading through their SVG and PGF backends, only to remember that Cairo is perfectly good at direct SVG and PDF [image] rendering (funny, because I was once a GNOME hacker and wrote Cairo bindings in a previous life. {sigh}), and sure enough **diagrams-cairo** is good to go.

One of the things we're going to need to do a lot of, however, is charts, and so here I am. Question is what Charts backend I should use? Something in my misplaced aesthetic sense makes me think that having all drawing code be in `Diagram B` would be ideal, but looking at **Charts-diagrams** I see heavy dependency on the Diagrams SVG backend and SVGfonts lashup, etc, which I more or less just skipped out on. Seems a bit silly to drag all that in when I have decided to use the Diagrams Cairo backend.

So should I just be using the **Charts-cairo** backend to your library and treat charts and graphics as separate artifacts? Or is there any reason to carve a pathway that has Charts using Diagrams, but the Cairo flavour thereof?

AfC

**Comment by timbod7** [comment]
I don't think I can give you a definitive answer on this. The diagrams backend for chart is an excellent bit of work done some years ago by Jan Bracker as a google summer of code project, but it suffers from two drawbacks:

* It's slow
* It relies on the external SVGFonts  library for text metrics

I'm sure the speed issue could be addressed with some effort, but no one has had the time or inclination to do the necessary profiling. I know that font loading is one part of this.

The latter issue is more fundamental - I've hoped for many years that the diagrams system would get support for calculations of text metrics, which is essential for generating decent charts. The user manual still says:

> Text objects take up no space!
> The main reason for this is that computing the size of some text in a given font is rather complicated, and diagrams cannot (yet) do it natively.

Of course, the diagrams backend also has a couple of benefits:

* it's dependencies are pure haskell, so its easier to build.
* you get a diagram out, which can be composed with other diagrams. 

If you can get away without these, then I'd probably stick to the straight cairo backend.

**Comment by afcowie** [comment]
> * Easier to build

Yeah, but I've got the build dependencies for **diagrams-cairo** sorted out (I'm on Linux so Cairo is a given, and Stack made it Just Work™) so using your original **Charts-cairo** backend will be fine too, I'm sure.

Thanks for the advice.

AfC
