### ISSUE TITLE
4 blank lines to stdout

### ISSUE THREAD

**Issue by IronGremlin** [timbod7/haskell-chart#168]
This is not exactly a show stopper, but it's driving me insane because I can't figure out what is causing it.

On windows 10, using the SVG backend, any time I generate a file, the program prints exactly 4 blank lines to stdout.

Here is my function:
```haskell
      makeChart f x z =
        let horsiz = if x == "hourly"
                        then 3200.0
                        else 96000.0
        in toFile (def{ _fo_size = (horsiz, 1200.0)}) (x<>".svg") $ do
            layout_title .= (x <> "Intervals")
            plot
              $ fmap plotBars
              $ (bars [x<>" counts"]
                 $! map (\(x,y) -> (utcToLocalTime f x, ([y] :: [Int]) ) )
                 . M.toList
                 $! z)
```

Everything else seems to work precisely as expected.

The number of lines is constant regardless of parameters passed to makeChart.

**Comment by tonyday567** [comment]
I've seen this recently, and trace it back to when a chart gets rendered, so either diagrams-svg, or maybe the SVGFonts library.  In my use cases, it's not always the same number of lines.

Very! annoying.

**Comment by timbod7** [comment]
I think it's a problem in the SVG fonts library. I've submitted a PR:

https://github.com/diagrams/SVGFonts/pull/23

**Comment by timbod7** [comment]
Will track on this duplicate issue:

https://github.com/timbod7/haskell-chart/issues/166
