### ISSUE TITLE
Chart-gtk3 support?

### ISSUE THREAD

**Issue by ghorn** [timbod7/haskell-chart#17]
is there gtk3 support planned?

**Comment by maaronking** [comment]
@ghorn 
I have been working on getting your chart-gtk package to work with gtk3.  I have gotten to the point where the gtk window is displayed but the drawing area is not getting painted. (Or at least that appears to be what is happening).  

Would you be interested in seeing the changes and seeing if you could take it that last 10%?

I am fairly new to Haskell and Gtk unfortunately.  I would also just be willing to try things based on suggestions once you see my changes...

Thanks in advance for your consideration.

**Comment by timbod7** [comment]
I'll take a quick look at your changes. I don't use gtk very much at all, but maybe I can see what is wrong.

**Comment by barryfm** [comment]
I forked the project and added a chart-gtk3 directory with the required changes.  I've used it on Fedora 27, and will be trying it on a variety of Linux  systems and ghc releases before suggesting a pull request,
but its there for people to comment on.
