### ISSUE TITLE
Ambiguous type variable ‘y200’ arising from a use of ‘toFile’

### ISSUE THREAD

**Issue by Ulrar** [timbod7/haskell-chart#173]
Hi,

I'm trying to export a file to test the library out using Diagrams, but I can't get it to work. Using Example 2 I got that : 

```haskell
  toFile def "test.png" $ do
    layoutlr_title .= "Active mem"
    layoutlr_left_axis . laxis_override .= axisGridHide
    layoutlr_right_axis . laxis_override .= axisGridHide
    plotLeft (line "Active" $ [L.map (\v -> ((utcToLocalTime utc $ time v) :: LocalTime, (fromIntegral $ value v) :: Double)) $ V.toList q])
```

I've had to convert my Int64 to a Double to remove one of the errors, but that still leaves one. I added the explicit :: LocalTime (since adding :: Double got rid of a very similar error) but it didn't change anything.
Here is the error : 

```
main.hs:33:3: error:
    • Ambiguous type variable ‘y200’ arising from a use of ‘toFile’
      prevents the constraint ‘(PlotValue y200)’ from being solved.
      Probable fix: use a type annotation to specify what ‘y200’ should be.
      These potential instances exist:
        instance PlotValue LogValue
          -- Defined in ‘Graphics.Rendering.Chart.Axis.Floating’
        instance PlotValue Percent
          -- Defined in ‘Graphics.Rendering.Chart.Axis.Floating’
        instance PlotValue Integer
          -- Defined in ‘Graphics.Rendering.Chart.Axis.Int’
        ...plus five others
        (use -fprint-potential-instances to see them all)
    • In the expression: toFile def "test.png"
...
```

No idea what y200 is referring to, any idea what I'm doing wrong ? Thanks

**Comment by timbod7** [comment]
I think the issue is that you are plotting a `LayoutLR` which has 3 type parameters: the type of the x axis, the type of the left y axis and the type of the right y axis, and you haven't constrained the type of the right y axis.

Either plot something on the right axis, or use the `Layout` type instead.

**Comment by Ulrar** [comment]
Ah, right. I didn't realize plotting only one side was different, I just took the example that looked like what I want and removed the side I don't need.

Anyway it compiles now, but I get a very little white square, doesn't look like any points got on it. Guess it's time to play with the different parameters
Thanks

**Comment by Ulrar** [comment]
Meh, png doesn't really work but svg works perfectly, so I'll go with that.
Thanks for your help !
