### ISSUE TITLE
Render a graph without a file

### ISSUE THREAD

**Issue by Ulrar** [timbod7/haskell-chart#174]
Hi,

I see plenty of stuff about how to render a graph and save it to a file in the doc, and it works fine, but is there a way to just get the png / svg / whatever in memory instead ?
I'd like to send that directly to the browser using the Snap Framework, so something like a ByteString would do. I imagine that's what runBackend is for, somehow ?
I'm using Diagrams but I don't mind changing to cairo if needed.

Thanks

**Comment by timbod7** [comment]
You can use the diagrams backend for this, via the `runBackendR` function. You:

* create a `Renderable` of your chart, using `layoutToRenderable` ( or `layoutLRToRenderable`) 
* convert the `Renderable` to a `Diagram`, using `runBackendR`
* use whatever diagrams library function is appropriate to turn the `Diagram` into your preferred in memory representation.
