### ISSUE TITLE
Upload new release on hackage

### ISSUE THREAD

**Issue by harendra-kumar** [timbod7/haskell-chart#200]
#192 seems to fix the build for ghc-8.6, can you please upload a new release on hackage with that fix and updated version bounds for dependencies.

**Comment by sgraf812** [comment]
:+1: from me

**Comment by timbod7** [comment]
Will do so in the next could of days.

**Comment by bravit** [comment]
Hi @timbod7, sorry for bugging you, could you please upload a new release?

**Comment by timbod7** [comment]
1.9.1 uploaded. Sorry it took so long.

(But see: https://github.com/timbod7/haskell-chart/issues/204)
