### ISSUE TITLE
Update Hackage version to Lens dependency < 4.18

### ISSUE THREAD

**Issue by schrammc** [timbod7/haskell-chart#203]
In the  Chart [cabal file ](https://github.com/timbod7/haskell-chart/blob/master/chart/Chart.cabal#L24), the dependency for lens is < 4.18. The same goes for Chart-cairo.

However in the latest version on Hackage the dependency is still < 4.17. Would it be possible to upload versions of Chart and Chart-cairo with the updated constraint to Hackage?

**Comment by schrammc** [comment]
This is probably a duplicate of #200

**Comment by timbod7** [comment]
1.9.1 uploaded. Sorry it took so long.

(But see: https://github.com/timbod7/haskell-chart/issues/204)
