### ISSUE TITLE
live plotting

### ISSUE THREAD

**Issue by teto** [timbod7/haskell-chart#226]
Hi,

I've started using chart in a software of mine and I am really happy with it. I now would like to plot the statistics live (refresh the plot with incoming data), e.g every 100ms for instance.  Is it possible with chart ? If yes how ? if not any recommand for a haskell library to do that ?

Cheers

**Comment by timbod7** [comment]
Which rendering backend are you using?

If you are using the gtk library for your application there's helper functions in this  module

https://github.com/timbod7/haskell-chart/blob/master/chart-gtk3/Graphics/Rendering/Chart/Gtk.hs

to render plots to on screen windows. These can be called periodically to update the display.

**Comment by teto** [comment]
will reopen if I have issues.
