### ISSUE TITLE
Customizing histograms (exposing `histToBins`).

### ISSUE THREAD

**Issue by shlok** [timbod7/haskell-chart#228]
I have customized my histogram to show the count above each bar. To do this, I currently have to (as far as I know) copy-paste the private [`histToBins`](https://hackage.haskell.org/package/Chart-1.9.3/docs/src/Graphics.Rendering.Chart.Plot.Histogram.html#histToBins) function.

How open would you be to publicly exposing the `histToBins` function?

**Comment by timbod7** [comment]
I think exposing that function would be fine.
