### ISSUE TITLE
New release or Hackage revision?

### ISSUE THREAD

**Issue by vaibhavsagar** [timbod7/haskell-chart#234]
Hi, you mentioned in https://github.com/timbod7/haskell-chart/issues/227#issuecomment-955800890 that you were open to doing a new release. Would this be possible so that I can use `Chart-diagrams` with GHC 8.10 in my project?

**Comment by vaibhavsagar** [comment]
I published [a new revision](https://hackage.haskell.org/package/Chart-diagrams-1.9.3/revision/3.cabal) in my capacity as a Hackage trustee. However, this only relaxes the upper bound on `diagrams-core`, so a new release with the other changes would still be welcome.

**Comment by bravit** [comment]
Fixed with https://hackage.haskell.org/package/Chart-diagrams-1.9.4

**Comment by vaibhavsagar** [comment]
Thanks!
