### ISSUE TITLE
Support GHC 9

### ISSUE THREAD

**Issue by andreasabel** [timbod7/haskell-chart#237]
Atm, GHC 9.0.1 and GHC 9.2.1 are excluded by the bounds on `base`.

**Comment by wrengr** [comment]
GHC 9.2.1 is also excluded by the bounds on `lens` which indirectly place bounds on `template-haskell` (whereas `lens-5.1` allows `template-haskell-2.18.0.0`).

**Comment by ulysses4ever** [comment]
It seems, all is well w.r.t GHC support on `master` now, so what remains is to do a Hackage release or even a revision, I believe, would suffice: it's only the `lens` bound that needs to be bumped.

**Comment by ulysses4ever** [comment]
A revision allowing to build with GHC 9.2 had been made today, so this ticket can be close I believe.

**Comment by andreasabel** [comment]
See https://hackage.haskell.org/package/Chart-1.9.3/revisions/
