### ISSUE TITLE
Allow lens-5.2

### ISSUE THREAD

**Issue by bgamari** [timbod7/haskell-chart#243]
A revision to allow `lens-5.2` would be great.

**Comment by jamesdbrock** [comment]
Yes please I would also like this.

**Comment by andreasabel** [comment]
I relaxed the lens bound on Hackage: https://hackage.haskell.org/package/Chart/revisions/

**Comment by philderbeast** [comment]
Is relaxing the lens upper bound something [Chart-diagrams](https://hackage.haskell.org/package/Chart-diagrams-1.9.4/dependencies) could also benefit from @andreasabel?

**Comment by andreasabel** [comment]
> Is relaxing the lens upper bound something [Chart-diagrams](https://hackage.haskell.org/package/Chart-diagrams-1.9.4/dependencies) could also benefit from @andreasabel?

Builds fine with `lens-5.2.2`, so I did the relaxation: https://hackage.haskell.org/package/Chart-diagrams-1.9.4/revisions/

**Comment by bravit** [comment]
Allowed in https://hackage.haskell.org/package/Chart-1.9.5
