### ISSUE TITLE
Support GHC 9.6

### ISSUE THREAD

**Issue by andreasabel** [timbod7/haskell-chart#248]
I figure a release supporting GHC 9.6 is already in the making...  Keep this open until the release has been made...

**Comment by andreasabel** [comment]
@timbod7 : Would it be possible to get a release now that works with GHC 9.6?  
Stackage nightly switched to GHC 9.6 and the Chart packages dropped out.
I guess highest priority would be to get the build failures fixed, e.g.:
- #243 
- #246

**Comment by bravit** [comment]
GHC 9.6 is supported in https://hackage.haskell.org/package/Chart-1.9.5
