### ISSUE TITLE
lens-5.3 out of bounds for Chart-cairo

### ISSUE THREAD

**Issue by andreasabel** [timbod7/haskell-chart#257]
https://github.com/commercialhaskell/stackage/issues/7408
- https://github.com/commercialhaskell/stackage/issues/7408

**Comment by ysangkok** [comment]
@bravit Would it be possible for you to make a revision to allow this new version?

**Comment by georgefst** [comment]
Plus `Chart` and `Chart-diagrams`...

**Comment by bravit** [comment]
Sorry folks, should be resolved by https://github.com/commercialhaskell/stackage/pull/7522.
