### ISSUE TITLE
Interest in zoomable Gtk plots

### ISSUE THREAD

**Issue by bryce-anderson** [timbod7/haskell-chart#54]
I've been playing with the idea of interactive plots with the Gtk backend in a branch, and I'm to a point where I want to know if they would be of interest to the project before I spend too much more time on it. Preliminary code can be found [here](https://github.com/bryce-anderson/haskell-chart/tree/topic/rangetransform), specifically [here](https://github.com/bryce-anderson/haskell-chart/blob/topic/rangetransform/chart-gtk/Graphics/Rendering/Chart/Gtk.hs#L138). 

Right now, functionality includes the ability to zoom in and out and a save menu option. Example code would look like 

``` haskell
import Graphics.Rendering.Chart.Gtk
import Graphics.Rendering.Chart.Easy

x :: [Double]
x = [1.9,1.92..18.5]

y :: [Double]
y = cos `map` x

main :: IO ()
main = toZoomableWindow 640 480 $ do
  layoutlr_title .= "Cos wave"
  plotLeft (line "cos" [ x `zip` y] )
  plotRight (line "1 + cos" [ x `zip` (((+1) . sin) `map` x)] )

```

The syntax is essentially unchanged with the exception that you call `toZoomableWindow` instead of `toWindow` and there must be an appropriate `Zoomable` instance.
I'm open to changing things, and it clearly needs to be cleaned up in terms of location of code; I just wanted to float the idea before getting too far.

**Comment by joe9** [comment]
I am looking to build an interactive realtime chart using haskell-chart. Your idea of chart-interactive sounds promising. Just want to check if you could share the code and I can see if I can take it forward?

@bryce-anderson

**Comment by bryce-anderson** [comment]
Hey @joe9, it looks like I still have that repo laying around: https://github.com/bryce-anderson/haskell-chart. I don't recall what state its in, but feel free to fork and do what you've gotta do! Just let me know if you end up with something useful.

**Comment by joe9** [comment]
Thanks @bryce-anderson

**Comment by Magalame** [comment]
@joe9 did you get to anything?

**Comment by joe9** [comment]
@Magalame , nope did not pursue it further.

**Comment by Magalame** [comment]
Well that was quick
