### ISSUE TITLE
NaNs causes infinite loop

### ISSUE THREAD

**Issue by yongqli** [timbod7/haskell-chart#60]
It looks like trying to plot a graph with NaNs causes the program to become unresponsive.

**Comment by timbod7** [comment]
I believe this is now fixed.

**Comment by andreasabel** [comment]
Thanks, no more crashing after the fix (Chart-1.3.3)!

**Comment by ghorn** [comment]
I just hit this issue on `Chart-1.8`

**Comment by timbod7** [comment]
Sigh....

Can you provide a test case?
