### ISSUE TITLE
Histograms

### ISSUE THREAD

**Issue by paul-r-ml** [timbod7/haskell-chart#72]
Hi Tim,

do you have plan to integrate histograms into haskell-charts ? 
For this need I currently use Ben Gamari's  Chart-Histogram package, which works well. Do you think it is better as a third party package, rather that directly provided as a feature of haskell-chart package ?

Cheers,

**Comment by timbod7** [comment]
I wasn't aware of the Chart-Histogram package. I'd be happy to see it merged in.

@bgamari : what do you think?

**Comment by bgamari** [comment]
@timbod7 sounds great. I think we briefly discussed this a few years back but I never got around to actually performing the merge.

**Comment by timbod7** [comment]
I'm happy to do so. Do you mind if I just snapshot the code?

**Comment by bgamari** [comment]
@timbod7, not at all.

**Comment by paul-r-ml** [comment]
You guys are awesome !  Cheers

**Comment by timbod7** [comment]
Hmmm. I've merged the code, and put up a quick test case:

https://github.com/timbod7/haskell-chart/compare/feature/histograms

Integration with the "Easy" modules doesn't seem obvious however, due the the fact that this module doesn't implement a instance of Default that works for all types. 

Thoughts or suggestions welcome.
