### ISSUE TITLE
Compatibility with newest Diagrams

### ISSUE THREAD

**Issue by marcinmrotek** [timbod7/haskell-chart#73]
Hello,

I was trying to compile some code using Chart and Diagrams under GHC 7.10 (with base 4.8), one thing lead to another, and I ended up compiling Chart-diagrams against the git version of Diagrams. The problem is, there are a lot of breaking changes, and the two don't quite fit. I tried to fix it, but I got stuck at runBackend* functions (GHC tries to identify "ChartBackend a" with "ChartBackend TextSize"), and the file rendering functions (SVG functions in Diagrams and SVGFonts seem to be completely different).

I just thought I'd share what I did manage to do:
* my Diagrams.hs: http://pastebin.com/XMgDWxGc
* diff to newest git version: http://pastebin.com/HEh0uz9S

Regards,
Marcin

**Comment by timbod7** [comment]
Thanks - I'll probably wait for an official new diagrams release before upgrading chart.

**Comment by marcinmrotek** [comment]
It's out ;)
