### ISSUE TITLE
A pure defaultEnv?

### ISSUE THREAD

**Issue by idontgetoutmuch** [timbod7/haskell-chart#75]
I find myself writing

```haskell
    denv :: DEnv
    denv = unsafePerformIO $ defaultEnv vectorAlignmentFns 500 500
```

so that I can create a pure `Diagram B R2`. With this I can then use the diagrams package to do a poor man's ggplot2 e.g.

https://idontgetoutmuch.files.wordpress.com/2014/06/a38b923b7522fc9d.png?w=1560

I also use BlogLiteratelyD where the diagram needs to be *not* in the IO monad.

I realise that the default fonts have to be read in but maybe the unsafePerformIO could be done in the chart package itself? Alternatively the fonts could be read in at compile time using Template Haskell.

**Comment by timbod7** [comment]
I don't really want to use unsafePerformIO to hide IO that is really occurring. Why is it that you can't do a single IO operation to load the fonts and setup the environment, and then procede purely?

In principle, I'm not against building the fonts in at compile time, however there's about 7.5M of data there currently, which is not insignificant.

**Comment by idontgetoutmuch** [comment]
I use http://hackage.haskell.org/package/BlogLiterately-diagrams to write my blog posts. It requires something of type ```Diagram B R2```. Unless I am missing something I don't think I have the opportunity to do any IO.

As an aside, I am curious to know why charts needs load fonts but diagrams itself doesn't.

**Comment by timbod7** [comment]
It looks like BlogLiterately-diagrams can do IO:

> In addition to simple diagrams, IO actions producing diagrams may also be used. In that case the IO 
> action will simply be run, and the resulting diagram rendered. This can be useful, for example, when
> producing a diagram built from some external data or using randomness. 

Charts needs to load fonts to workaround the fact that diagrams has no support for text metrics, ie it can't tell a use how big an textual element will be. This is essential in layout out charts cleanly.

**Comment by idontgetoutmuch** [comment]
Thanks for this. I did not know that despite having used BlogLiteratelyD for years. I will try it out this week and then close the ticket.

**Comment by timbod7** [comment]
Also, this recent commit https://github.com/timbod7/haskell-chart/commit/a4af95b419b9d810d7cc2d0f3a8937abe9d85aa0 provides a pure function that can create a DEnv, letting the caller provide the fonts.
