### ISSUE TITLE
Bar chart legend

### ISSUE THREAD

**Issue by paul-r-ml** [timbod7/haskell-chart#76]
Hi Tim,

I have a problem with legend overflowing the chart area on bar charts. I am attaching an example of a problematic rendering (the name on the right, does not print properly).  Can I hint Chart to avoid this behaviour ? Is this a bug that could be fixed ?

Cheers, all the best.

![bars](https://cloud.githubusercontent.com/assets/280323/6637813/35870208-c97f-11e4-92f8-2866fa606531.png)

**Comment by timbod7** [comment]
You should be able to fix this by setting the legend orientation to LORows 2

```
-- | Legends can be constructed in two orientations: in rows
-- (where we specify the maximum number of columns), and in
-- columns (where we specify the maximum number of rows)
data LegendOrientation = LORows Int | LOCols Int
```
