### ISSUE TITLE
lens-4.8 compatability

### ISSUE THREAD

**Issue by ghorn** [timbod7/haskell-chart#78]

**Comment by timbod7** [comment]
I've pushed this change in an attempt to use lens 4.8:

https://github.com/timbod7/haskell-chart/commit/d8d89384b377caf5cfee2db726899e1ae49bf277

However, as you can see there is still a problem with diagrams not supporting 4.8:

```
07:24:21 (master) ~/repos/chart$ cabal install --dependencies-only --constraint lens==4.8
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: diagrams-core-1.2.0.5/installed-5c2... (user goal)
next goal: lens (user goal)
rejecting: lens-4.7/installed-c00... (global constraint requires ==4.8)
rejecting: lens-4.8 (conflict: diagrams-core => lens==4.7/installed-c00...)
rejecting: lens-4.7, 4.6.0.1, 4.6, 4.5, 4.4.0.2, 4.4.0.1, 4.4, 4.3.3, 4.3.2,
4.3.1, 4.3, 4.2, 4.1.2.1, 4.1.2, 4.1.1, 4.1, 4.0.7, 4.0.6, 4.0.5, 4.0.4,
4.0.3, 4.0.2, 4.0.1, 4.0, 3.10.3, 3.10.2, 3.10.1, 3.10.0.1, 3.10, 3.9.2,
3.9.1, 3.9.0.3, 3.9.0.2, 3.9.0.1, 3.9, 3.8.7.3, 3.8.7.2, 3.8.7.1, 3.8.7,
3.8.6, 3.8.5, 3.8.4, 3.8.3, 3.8.2, 3.8.1, 3.8.0.2, 3.8.0.1, 3.8, 3.7.6, 3.7.5,
3.7.4, 3.7.3, 3.7.2, 3.7.1.2, 3.7.1.1, 3.7.1, 3.7.0.2, 3.7.0.1, 3.7, 3.6.0.4,
3.6.0.3, 3.6.0.2, 3.6.0.1, 3.6, 3.5.1, 3.5, 3.4, 3.3, 3.2, 3.1, 3.0.6, 3.0.5,
3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0, 2.9, 2.8, 2.7.0.1, 2.7, 2.6.1, 2.6, 2.5,
2.4.0.2, 2.4, 2.3, 2.2, 2.1, 2.0, 1.9.1, 1.9, 1.8, 1.7.1, 1.7, 1.6, 1.5,
1.4.1, 1.4, 1.3.1, 1.3, 1.2, 1.1.1, 1.1, 1.0.3, 1.0.2, 1.0.1, 1.0, 0.9, 0.8,
0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1 (global constraint requires ==4.8)
Backjump limit reached (change with --max-backjumps).

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

I think we need to wait for a new release of diagrams that supports lens-4.8

**Comment by peddie** [comment]
I cloned this repo and was able to build `Chart,` `Chart-diagrams`, `Chart-cairo` and `Chart-gtk` in their own sandbox by bumping the upper bound on the `lens` version from 4.7 or 4.8 to 4.9 everywhere.  I was able to run the tests (with `cabal configure -fcairo -fdiagrams -fgtk`) and get a successful return code.  I was also able to run the programs in `wiki-examples` without any failed return codes.  I'm using `cabal-install` version 1.22.2.0.  It looks like it installed `lens` 4.8 and 4.7 at different points in the process, since they're both in the sandbox at the end:

     $ cabal exec ghc-pkg list
     [ global package db elided ]
     /home/peddie/programming/haskell/haskell-chart/.cabal-sandbox/i386-linux-ghc-7.8.3-packages.conf.d
      Boolean-0.2.3
      Chart-1.3.3
      Chart-cairo-1.3.3
      Chart-diagrams-1.3.3
      Chart-gtk-1.3.3
      Chart-simple-1.3.3
      JuicyPixels-3.2.3.1
      MemoTrie-0.6.2
      NumInstances-1.4
      OneTuple-0.2.1
      SVGFonts-1.4.0.3
      StateVar-1.1.0.0
      active-0.1.0.18
      adjunctions-4.2
      ansi-terminal-0.6.2.1
      ansi-wl-pprint-0.6.7.2
      attoparsec-0.12.1.5
      base64-bytestring-1.0.0.1
      bifunctors-4.2.1
      blaze-builder-0.3.3.4
      blaze-markup-0.6.3.0
      blaze-svg-0.3.4.1
      cairo-0.13.1.0
      colour-2.3.3
      comonad-4.2.5
      contravariant-1.3.1
      data-default-class-0.0.1
      diagrams-cairo-1.2.0.6
      diagrams-core-1.2.0.5
      diagrams-lib-1.2.0.8
      diagrams-postscript-1.1.0.4
      diagrams-svg-1.1.0.4
      distributive-0.4.4
      dlist-0.7.1.1
      dual-tree-0.2.0.5
      exceptions-0.8.0.2
      fingertree-0.1.0.2
      free-4.11
      gio-0.13.0.4
      glib-0.13.1.0
      groups-0.4.0.0
      gtk-0.13.4
      hashable-1.2.3.2
      intervals-0.7.1
      kan-extensions-4.2.1
      lens-4.7
      lens-4.8
      monoid-extras-0.3.3.5
      mtl-2.2.1
      nats-1
      newtype-0.2
      operational-0.2.3.2
      optparse-applicative-0.11.0.2
      pango-0.13.0.5
      parallel-3.2.0.6
      parsec-3.1.9
      prelude-extras-0.4
      primitive-0.5.4.0
      profunctors-4.4.1
      random-1.1
      reflection-1.5.1.2
      scientific-0.3.3.8
      semigroupoids-4.3
      semigroups-0.16.2.2
      split-0.2.2
      statestack-0.2.0.3
      stm-2.4.4
      tagged-0.7.3
      text-1.2.0.4
      transformers-0.4.3.0
      transformers-compat-0.4.0.4
      tuple-0.3.0.2
      unordered-containers-0.2.5.1
      utf8-string-1
      vector-0.10.12.3
      vector-space-0.9
      vector-space-points-0.2.1
      void-0.7
      xml-1.3.14
      zlib-0.5.4.2

**Comment by timbod7** [comment]
Yes - that worked for me also. But it seems to me that we haven't solved the problem until we can build with lens 4.8 alone?

**Comment by peddie** [comment]
I should have noted that `lens` 4.7 only showed up for the diagrams backend.

You're right that it's not ready as-is.  I was working on my post for over an hour in an attempt to narrow down any problems and didn't see that you had updated this ticket already.  Apologies for the noise :)

**Comment by FranklinChen** [comment]
diagrams is out now and supports lens 4.9, so I think it's time to update this too.

**Comment by FranklinChen** [comment]
Ah, I see there is already a pull request for this: https://github.com/timbod7/haskell-chart/pull/79

**Comment by timbod7** [comment]
When you say "diagrams is out now", which version are you referring to?

**Comment by FranklinChen** [comment]
`diagrams` 1.3 https://github.com/diagrams/diagrams/commit/e4186d86278e83a7957f06e3b522f018c195edad

**Comment by timbod7** [comment]
The library is now compatible with lens >= 3.9 && < 4.12
