### ISSUE TITLE
Compile fonts shipped with chart-diagrams into library/binary at compile time

### ISSUE THREAD

**Issue by axman6** [timbod7/haskell-chart#84]
Currently the fonts included with chart-diagrams are installed in a directory relative to either your .cabal or ~/Library/Haskell on OS X directory, or inside your cabal sandbox when binaries are built. This causes issues with deploying apps using chart-diagrams because the paths that are searched for are hard coded to absolute paths meaning that they must be installed on the production environment at exactly the same path.

I've seen that there are some functions which allow you to specify the paths to fonts, but to keep the interface easy to use with the default fonts, I feel that including the SVG fonts at compile time using something like [include-file](https://hackage.haskell.org/package/include-file) and then having [defaultFonts](https://github.com/timbod7/haskell-chart/blob/ee4549a8260fe9804c42e16b08d4fc270b066c66/chart-diagrams/Graphics/Rendering/Chart/Backend/Diagrams.hs#L244) use those included fonts would mean that no extra setup is necessary in when deploying binaries based on chart-diagrams.

The changes, I hope, would be minimal (but I haven't tried making the change properly myself yet)

```haskell

defaultFonts :: IO (FontStyle -> DFont)
defaultFonts = do
  serifR   <- loadDefaultFont "fonts/LinLibertine_R.svg"
  serifRB  <- loadDefaultFont "fonts/LinLibertine_RB.svg"
  serifRBI <- loadDefaultFont "fonts/LinLibertine_RBI.svg"
  serifRI  <- loadDefaultFont "fonts/LinLibertine_RI.svg"
  sansR   <- loadDefaultFont "fonts/SourceSansPro_R.svg"
  sansRB  <- loadDefaultFont "fonts/SourceSansPro_RB.svg"
  sansRBI <- loadDefaultFont "fonts/SourceSansPro_RBI.svg"
  sansRI  <- loadDefaultFont "fonts/SourceSansPro_RI.svg"
  monoR  <- loadDefaultFont "fonts/SourceCodePro_R.svg"
  monoRB <- loadDefaultFont "fonts/SourceCodePro_RB.svg"
```

would become something like

```haskell
defaultFonts :: IO (FontStyle -> DFont)
defaultFonts = do
  let
    $(includeFileInSource "fonts/LinLibertine_R.svg" "serifR")
    $(includeFileInSource "fonts/LinLibertine_RB.svg" "serifRB")
    $(includeFileInSource "fonts/LinLibertine_RBI.svg" "serifRBI")
    $(includeFileInSource "fonts/LinLibertine_RI.svg" "serifRI")
    $(includeFileInSource "fonts/SourceSansPro_R.svg" "sansR")
    $(includeFileInSource "fonts/SourceSansPro_RB.svg" "sansRB")
    $(includeFileInSource "fonts/SourceSansPro_RBI.svg" "sansRBI")
    $(includeFileInSource "fonts/SourceSansPro_RI.svg" "sansRI")
    $(includeFileInSource "fonts/SourceCodePro_R.svg" "monoR")
    $(includeFileInSource "fonts/SourceCodePro_RB.svg" "monoRB")
```

**Comment by timbod7** [comment]
It might be a good idea to have this in a separate package, to give developers the choice of either installing the font files, or embedded them in the exe.

**Comment by axman6** [comment]
I guess the obvious choice would be the SVGFonts package with a cabal flag?

**Comment by timbod7** [comment]
I've just pushed a patch (a4af95b419b9d810d7cc2d0f3a8937abe9d85aa0) that simplifies and improves font handling with diagrams. Less fonts are loaded by default, and the the caller now has the option of loading the fonts before calling the library. That should make it possible to have you application manage fonts as it needs?

**Comment by axman6** [comment]
Sorry for not getting back to you sooner. I should have a chance to look into this some time this week and I'll let you know how it goes.

**Comment by axman6** [comment]
"This week" - Sorry about that. We have updated to using this new implementation, and things are now working well. I notice that the memory usage is quite hight, even when using only a subset of the fonts (Most of this stolen from your code):

```haskell
loadFonts :: Config -> IO (FontSelector Double)
loadFonts conf = do
    fontPath <- C.lookupDefault "fonts" conf "font-path"

    [
       sansR
     , sansRB
     , sansRBI
     , sansRI
     ] <- mapConcurrently (F.loadFont . (fontPath ++))
                    [ "/SourceSansPro_R.svg"
                    , "/SourceSansPro_RB.svg"
                    , "/SourceSansPro_RBI.svg"
                    , "/SourceSansPro_RI.svg"
                    ]
    putStrLn "loaded fonts"

    let selectFont :: FontStyle -> F.PreparedFont Double
        selectFont fs = alterFontFamily "sans-serif" $ case (_font_name fs, _font_slant fs, _font_weight fs) of
          (_, FontSlantNormal , FontWeightNormal) -> sansR
          (_, FontSlantNormal , FontWeightBold  ) -> sansRB
          (_, FontSlantItalic , FontWeightNormal) -> sansRI
          (_, FontSlantOblique, FontWeightNormal) -> sansRI
          (_, FontSlantItalic , FontWeightBold  ) -> sansRBI
          (_, FontSlantOblique, FontWeightBold  ) -> sansRBI

    return selectFont
```

Uses something like 600MB. This is ok in our case, but it may not be for other users.

**Comment by timbod7** [comment]
Closing this issue as the original problem is resolved, and the discussion on font handling performance with diagrams is ongoing in this issue: https://github.com/timbod7/haskell-chart/issues/105
