### ISSUE TITLE
Example charts sometimes don't correspond to code.

### ISSUE THREAD

**Issue by jonathanknowles** [timbod7/haskell-chart#87]
While browsing through the examples, I noticed that some of the charts don't exactly correspond with the sample code given. For example:

In [example 1] (https://github.com/timbod7/haskell-chart/wiki/example-1) ("Amplitude Modulation") the graph is plotted with red points, but the first block of code (written with the easy helper functions) contains no code for specifying that points be plotted with the colour red. When the code is compiled and run, it produces a graph whose points are plotted with the colour green (the default).

It appears that the second block of code (written without the easy helper functions) **does** produce the correct output.

It would be useful if both code sections produced the same output, so that users could compare how to produce the same effect with both techniques.

(For example, it's not clear to me how I would specify that points are plotted with the colour red when using the easy helper functions.)

**Comment by timbod7** [comment]
I think this has happened because the default colors in the monadic API have changed since the example was written. It's quite time consuming to keep this wiki documentation up to date (or to even notice that it has drifted out of date).

I've updated the example code.

**Comment by jonathanknowles** [comment]
Hi Tim
Thanks for your reply!
I appreciate that updating documentation can be very time consuming.
However, I would like to offer my thanks and encouragement for providing such good examples -- they are extremely helpful for people wishing to learn the library.
All the best
Jonathan
