### ISSUE TITLE
chart-gtk is missing from the latest  stackage

### ISSUE THREAD

**Issue by barryfm** [timbod7/haskell-chart#94]
The chart-gtk package is not in the GHC 7.10.2 stackage LTS or Nightly.  Everything seems compatable except the Simple interface which has been withdrawn.  I'm using the cabal system setup without problems.

Haskell-chart and its other backends are in the LTS.  Is there a reason chart-gtk it is no longer maintained there?

**Comment by timbod7** [comment]
What has to happen to do this?

I endeavour to keep the chart library compatible with stackage. I'm
generally happy to leave it to others to put it there.

**Comment by timbod7** [comment]
If changes are needed to the library let me know. Otherwise I am happy for anyone to add chart-gtk to stackage if they need it.
