### ISSUE TITLE
Haskell-chart performance issue

### ISSUE THREAD

**Issue by warreee** [timbod7/haskell-chart#97]
Hello everyone

I'm trying to plot a value for every second of the day. This means I have an array of 24 * 60 * 60 = 86400 different values. I'm able to plot the values after compiling but it takes 3min30s to do so.
Does anyone have ideas how I can improve the speed?
I already tried it with both Int and Double values.

```haskell
import Graphics.Rendering.Chart.Easy
import Graphics.Rendering.Chart.Backend.Diagrams
import Data.Time.LocalTime
import Control.Exception
import Control.Monad


makePairs :: [Int] -> [(Int,Int)]
makePairs xs = [(x,(xs !! x)) | x <- [0..((length xs)-1)]]

main = do
    input <- readFile "testdata.csv"
    let numbers = map (read::String->Int) (map last $ map words $ lines input) 
    let pairs = makePairs numbers
    toFile def "example1_big.png" $ do
    layout_title .= "Bezettingsgraad"
    setColors [opaque blue, opaque red]
    plot (line "Bezoekers" [pairs])
```
Thanks

**Comment by timbod7** [comment]
The diagrams backend is quite slow. You should see better than an order of magnitude speed improvement if you use the cairo backend.

**Comment by warreee** [comment]
Hey Timbod, I just ran it with the cairo backend, and indeed it's twice as fast.
That's the fastest it can get, I suppose?

**Comment by timbod7** [comment]
I think your makePairs function will be slow -  O(n^2).  The !! operator must linearly traverse the list each time it is called. It will be quicker if you wrote it like this:

```
makePairs xs = zip [0,1..] xs
```

**Comment by warreee** [comment]
Thanks Tim, that was a really stupid mistake of me.
It solved the problem, I'm now able to plot the chart in less than a second. :-)
