### ISSUE TITLE
lens 4.13 compatability

### ISSUE THREAD

**Issue by ghorn** [timbod7/haskell-chart#98]
`4.13` is out, chart-cairo at least is bounded to `< 4.13`. I have not tested with `4.13`.

**Comment by DanBurton** [comment]
Bump. It looks like this is already done in Chart-cairo and we're just waiting for a hackage release.

**Comment by timbod7** [comment]
Hmm - looks like I left this out of the last hackage release...  will add Chart-cairo

**Comment by DanBurton** [comment]
Please do, thanks!

**Comment by timbod7** [comment]
Done. Sorry for the delay.
